services:
  nginx:
    container_name: nginx
    image: futarincontainerregistry.azurecr.io/nginx:latest
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    container_name: futarin-api
    image: futarincontainerregistry.azurecr.io/futarin-api:latest
    ports:
      - "8000:8000"
    expose:
      - 8000
    networks:
      - nginx-network

networks:
  nginx-network:
    driver: bridge

