services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx-network

  api:
    container_name: api
    image: futarin-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: _docker/api/Dockerfile
    expose:
      - 8000
    networks:
      - nginx-network

  voicevox:
    container_name: voicevox
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '50021:50021'
    tty: true

networks:
  nginx-network:
    driver: bridge

