services:
  #  nginx:
  #    container_name: nginx
  #    image: nginx:alpine
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - api
  #    volumes:
  #      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
  #    networks:
  #      - nginx-network

  api:
    container_name: api
    image: futarin-api
    environment:
      - IS_DEV_MODE=0
    env_file:
      - .env
    build:
      context: .
      args:
        - ENV=production
      dockerfile: _docker/api/Dockerfile
    ports:
      - "80:80"
    expose:
      - 8000
    networks:
      - nginx-network

  db:
    image: mysql:latest
    container_name: mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: ${TZ}
    command:  mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./_docker/db/data:/var/lib/mysql
      - ./_docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./_docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    container_name: test_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST = db
    ports:
      - 8080:80

        #  azurite:
        #    image: mcr.microsoft.com/azure-storage/azurite
        #    ports:
        #      - "10000:10000" # Blob
        #    volumes:
        #      - ./data:/data
        #    command: "azurite-blob --blobHost 0.0.0.0 --location /data --debug /data/debug.log"

networks:
  nginx-network:
    driver: bridge

volumes:
  mysql_host:
