services:
  #  nginx:
  #    container_name: nginx
  #    image: nginx:alpine
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - api
  #    volumes:
  #      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
  #    networks:
  #      - nginx-network

  api:
    container_name: api
    image: futarin-api
    environment:
      - IS_DEV_MODE=0
    env_file:
      - .env
    build:
      context: .
      args:
        - ENV=production
      dockerfile: _docker/api/Dockerfile
    ports:
      - "80:80"
    expose:
      - 8000
    networks:
      - nginx-network

  db:
    container_name: mysql-container
    build:
      context: .
      dockerfile: ./_docker/mysql/Dockerfile
    platform: linux/x86_64
    ports:
      - 3306:3306
    env_file:
      - ./.env_mysql
    volumes:
      - mysql_data:/var/lib/mysql
    

        #  azurite:
        #    image: mcr.microsoft.com/azure-storage/azurite
        #    ports:
        #      - "10000:10000" # Blob
        #    volumes:
        #      - ./data:/data
        #    command: "azurite-blob --blobHost 0.0.0.0 --location /data --debug /data/debug.log"

networks:
  nginx-network:
    driver: bridge

volumes:
  mysql_data:
