services:
  #  nginx:
  #    container_name: nginx
  #    image: nginx:alpine
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - api
  #    volumes:
  #      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
  #    networks:
  #      - nginx-network

  api:
    container_name: api
    image: futarin-api
    environment:
      - IS_DEV_MODE=0
    env_file:
      - .env
    build:
      context: .
      args:
        - ENV=production
      dockerfile: _docker/api/Dockerfile
    ports:
      - "80:8000"
        #    expose:
        #      - 8000
        #    networks:
        #      - nginx-network

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "futaringoto_db"
      TZ: "Asia/Tokyo"
    cap_add:
      - SYS_NICE
    volumes:
      - db-data:/var/lib/mysql
      # - ./_docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      # - ./_docker/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3001:80"
volumes:
  db-data:

        #networks:
        #  nginx-network:
        #    driver: bridge
