services:
  #  nginx:
  #    container_name: nginx
  #    image: nginx:alpine
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - api
  #    volumes:
  #      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
  #    networks:
  #      - nginx-network

  api:
    container_name: api
    image: futarin-api
    environment:
      - IS_DEV_MODE=0
    env_file:
      - .env
    build:
      context: .
      args:
        - ENV=production
      dockerfile: _docker/api/Dockerfile
    ports:
      - "80:8000"
        #    expose:
        #      - 8000
        #    networks:
        #      - nginx-network

        #networks:
        #  nginx-network:
        #    driver: bridge
