services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - nginx-network

  api:
    container_name: api
    image: futarin-api
    env_file:
      - .env
    build:
      context: .
      dockerfile: _docker/api/Dockerfile
    expose:
      - 8000
    networks:
      - nginx-network
    volumes:
      - ./api:/api
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80", "--reload"]

        #  azurite:
        #    image: mcr.microsoft.com/azure-storage/azurite
        #    ports:
        #      - "10000:10000" # Blob
        #    volumes:
        #      - ./data:/data
        #    command: "azurite-blob --blobHost 0.0.0.0 --location /data --debug /data/debug.log"

networks:
  nginx-network:
    driver: bridge

