name: CI

on:
  push:
  pull_request:
    paths:
      - "api/**.py"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repositry
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          touch .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "VOICEVOX_API_KEY=${{ secrets.VOICEVOX_API_KEY }}" >> .env

      - name: Run docker-compose Build
        run: docker compose -f docker-compose.yml -f docker-compose.dev.yml up --build -d
      - name: Run flake8
        run: docker compose run --entrypoint "flake8" api

      - name: Run test
        run: docker compose run --entrypoint "pytest" api
